### ISSUE TITLE
Review notes

### ISSUE THREAD

**Issue by chrisvfritz** [jakee246/project3#1]
Same problem as earlier with invalid HTML. Let me know when the code has been updated and don't hesitate if you have any questions.

**Comment by jakee246** [comment]
Hi,

I see that the HTML is invalid but I am not 100% sure what that means. The
code is correct and the page is displaying?

Thank you, Jake

**Comment by chrisvfritz** [comment]
[This slide group on Codekwondo](http://codekwondo.herokuapp.com/skills/37/presentation#/1) should help explain why valid HTML is important. Let me know if that makes sense to you.

In this case, it looks like you can fix the error by adding a doctype declaration to your HTML pages. [See here](http://www.w3schools.com/tags/tag_DOCTYPE.asp) for more info on doctype declarations.

**Comment by jakee246** [comment]
Does fixing this remove the strike that I received on Project 3? 

Thank you, Jake

**Comment by chrisvfritz** [comment]
Since the project is _mostly_ done in your case, I'll be happy to withdraw the strike if you can fix it promptly.

**Comment by jakee246** [comment]
http://validator.w3.org/check?uri=https%3A%2F%2Ftc359project3.herokuapp.com%2F&charset=%28detect+automatically%29&doctype=Inline&group=0&user-agent=W3C_Validator%2F1.3+http%3A%2F%2Fvalidator.w3.org%2Fservices

Everything checked out and it shows it's validated. Problem should be
solved. Thank you for allowing me the chance to correct my mistake!

Thank you, Jake

**Comment by chrisvfritz** [comment]
:+1: Much better!
